// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRXEHGW3WLNud90u-i7cdQ2hIpLLnPxrg',
    appId: '1:354677682673:android:f56377508a3cc3a2e21450',
    messagingSenderId: '354677682673',
    projectId: 'clubs-app-7b3b1',
    storageBucket: 'clubs-app-7b3b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNFvdcK1NRNj39hHqLPNBwReFl-0T1qhI',
    appId: '1:354677682673:ios:2f1a97cb96f21a7ee21450',
    messagingSenderId: '354677682673',
    projectId: 'clubs-app-7b3b1',
    storageBucket: 'clubs-app-7b3b1.firebasestorage.app',
    iosBundleId: 'com.example.clubApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNFvdcK1NRNj39hHqLPNBwReFl-0T1qhI',
    appId: '1:354677682673:ios:2f1a97cb96f21a7ee21450',
    messagingSenderId: '354677682673',
    projectId: 'clubs-app-7b3b1',
    storageBucket: 'clubs-app-7b3b1.firebasestorage.app',
    iosBundleId: 'com.example.clubApp',
  );
}
